### ISSUE TITLE
Swift 4.0 的适配

### ISSUE THREAD

**Issue by carping** [Binglin/MappingAce#5]
当我用在 swift4.0 的时候  数字的扩展  那一块有问题      我的能力修改不了。。。。。

**Comment by Binglin** [comment]
swift4.0我自己是用过的，没有出现什么问题，需要把你的问题详细说明一下哦

**Comment by Binglin** [comment]
@carping swift4.0我自己是用过的，没有出现什么问题，需要把你的问题详细说明一下哦

**Comment by carping** [comment]
![wechatimg1364](https://user-images.githubusercontent.com/29570566/30331512-9aec3c60-980a-11e7-82f5-300235f57c84.jpeg)

<img width="888" alt="wx20170912-223102 2x" src="https://user-images.githubusercontent.com/29570566/30331540-ae813ff0-980a-11e7-91ba-7e2700b0bf3c.png">

**Comment by carping** [comment]
把 Demo 下载下来的时候   把 版本改成 Swift 4.0 就会报下面的这个错误. 

还有大神   可以给非空的  属性 赋值默认属性吗.   有时候后台 会删除字段    前台 会 carch

<img width="768" alt="wx20170925-231531 2x" src="https://user-images.githubusercontent.com/29570566/30816075-811045ec-a247-11e7-8095-c84772c72e6a.png">

**Comment by Binglin** [comment]
@carping  可以有默认值 详见 https://github.com/Binglin/MappingAce#struct-or-class-has-default-property-value
